#!/usr/bin/env bash
# MIT © Sindre Sorhus - sindresorhus.com

# git hook to run a command after `git pull` if a specified file was changed
# Run `chmod +x post-merge` to make it executable then put it into `.git/hooks/`.

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

changed() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}
echo 'post-merge started';

if changed 'package-lock.json'; then
	echo "[package-lock.json] changed: Installing npm dependencies..."
 	npm install
fi

if changed 'composer.lock'; then 
	echo "[composer.lock] changed: Installing composer dependencies..."
	composer install
fi

if changed 'database/migrations'; then
  echo "Migrations are changed: Migrating..."
  php artisan migrate
fi

if changed 'database/seeds'; then
  echo "Seeds are changed: Seeding new data..."
  php artisan db:seed
fi

echo 'post-merge finished';
